# Generated by Django 3.2.17 on 2024-02-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargo', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.CharField(max_length=20, unique=True)),
                ('price', models.FloatField(default=7.0)),
                ('hasArived', models.BooleanField(default=False)),
                ('source_address', models.CharField(max_length=50)),
                ('destination_address', models.CharField(max_length=50)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('sending_date', models.DateField()),
                ('cargo', models.ManyToManyField(related_name='cargo_name', to='cargo.Cargo')),
                ('category', models.ManyToManyField(related_name='sipping_category', to='category.Category')),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
    ]
