# Generated by Django 3.2.17 on 2024-02-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargoID', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('supplier_address', models.CharField(max_length=25)),
                ('supplier_phone', models.CharField(max_length=25)),
                ('supplier_email', models.EmailField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(related_name='cargo_category', to='category.Category')),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
    ]
